const LIMITS = {
    MAX_USER_PER_WORKSPACE: 30,
    MAX_TEAMS_PER_WORKSPACE: 5,
    MAX_TEAM_MEMBERS_PER_TEAM: 15,
    MAX_SUGGESTIONS_PER_MEETING: 10,
    MAX_AUDIO_FILE_SIZE_MB: 25,
    MAX_MEETINGS_PER_WORKSPACE: 200,
    MAX_TASKS_PER_USER: 50,
};

module.exports = { LIMITS };